name: SQL Linting

on: [pull_request]

# THIS IS WHERE THE 'permissions' BLOCK GOES
# permissions:
#   contents: read
#   checks: write # Crucial for posting the sqlfluff annotations to the PR

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
            files: models/**/*.sql

      - name: Install SQLFluff
        run: "pip install sqlfluff==3.0"
      - name: Lint models
        run: "sqlfluff lint --format github-annotation-native models"


#py -m sqlfluff lint models